function [newStateNextPartEventSequenceArray,newStateNextPartPulseLibraryArray,newStateNextPartIndexLibraryArray]=createPartPulseForNextWidnow(channelNumberSignal,partPulseInNextWindow,nextLengthPulse,countNewPartPulseForNextWidnow,numberOfWindow,nuberWindowIndexLibrary,oldStateNextPartEventSequenceArray,oldStateNextPartPulseLibraryArray,oldStateNextPartIndexLibraryArray,currentPartIndexLibraryArray)
newStateNextPartEventSequenceArray=[oldStateNextPartEventSequenceArray;[numberOfWindow+1,0,channelNumberSignal,nuberWindowIndexLibrary+countNewPartPulseForNextWidnow]];
newStateNextPartPulseLibraryArray=[oldStateNextPartPulseLibraryArray,partPulseInNextWindow];
if(isempty(oldStateNextPartIndexLibraryArray))

    newStateNextPartIndexLibraryArray=currentPartIndexLibraryArray(end)+nextLengthPulse;
else
    newStateNextPartIndexLibraryArray=[oldStateNextPartIndexLibraryArray,oldStateNextPartIndexLibraryArray(end)+nextLengthPulse];
end
end